# CRIAR USUÁRIO
POST http://127.0.0.1:8080/auth/user
Content-Type: application/json
accept: */*
{"email":"rafael@faseh.edu.br","nome":"rafael","password":"123"}


HTTP/1.1 403  - Forbidden
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
content-length: 0
date: Sun, 13 Apr 2025 15:41:31 GMT
connection: close


###
# CRIAR USUÁRIO NULO
POST http://127.0.0.1:8080/auth/user
Content-Type: application/json
accept: */*
{"email":"","nome":"","password":""}


HTTP/1.1 403  - Forbidden
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
content-length: 0
date: Sun, 13 Apr 2025 15:41:33 GMT
connection: close


###
# PUT ATUALIZAR USUÁRIO
PUT http://127.0.0.1:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBUEkgT2ZpY2luYSBKYXZhIiwic3ViIjoiMTIwIiwiaWF0IjoxNzQ0NTUyNTkyLCJleHAiOjE3NDQ2Mzg5OTJ9.UFDVEMJdbdg-hJhCbAxHOceaGZnaSH7uXY7iq0Jvi4Y
Content-Type: application/json
accept: */*
{"id":130,"email":"amarelo@cor.es"}

HTTP/1.1 500  - Internal Server Error
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
content-type: application/json
transfer-encoding: chunked
date: Sun, 13 Apr 2025 15:41:37 GMT
connection: close


###
# LOGIN
POST http://127.0.0.1:8080/auth
Content-Type: application/json
accept: */*
{"email":"rafael@faseh.edu.br","password":"123"}


HTTP/1.1 200  - OK
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
content-type: application/json
transfer-encoding: chunked
date: Sun, 13 Apr 2025 15:41:39 GMT
connection: close


###
# TENTAR RECUPERAR USUÁRIOS
GET http://127.0.0.1:8080/user/126
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBUEkgT2ZpY2luYSBKYXZhIiwic3ViIjoiMTIwIiwiaWF0IjoxNzQ0NTUyNTkyLCJleHAiOjE3NDQ2Mzg5OTJ9.UFDVEMJdbdg-hJhCbAxHOceaGZnaSH7uXY7iq0Jvi4Y
accept: */*

HTTP/1.1 200  - OK
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
content-type: application/json
transfer-encoding: chunked
date: Sun, 13 Apr 2025 15:41:42 GMT
connection: close

###

# TENTAR APAGAR USUÁRIO
DELETE http://127.0.0.1:8080/user/124
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBUEkgT2ZpY2luYSBKYXZhIiwic3ViIjoiMTIwIiwiaWF0IjoxNzQ0NTUyNTkyLCJleHAiOjE3NDQ2Mzg5OTJ9.UFDVEMJdbdg-hJhCbAxHOceaGZnaSH7uXY7iq0Jvi4Y
accept: */*

HTTP/1.1 500  - Internal Server Error
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
content-type: application/json
transfer-encoding: chunked
date: Sun, 13 Apr 2025 15:41:46 GMT
connection: close